// Source of truth for the 2026-2027 year page.
// assets/year.js renders session cards, sketch cards, slide controls, and search
// from this data. Update this file before editing repeated markup by hand, then
// run npm run build:index and npm run check.
window.COURSE_DATA = {
  year: "2026-2027",
  lab: {
    defaultSketch: "face-exercise",
  },
  currentSession: {
    id: "session-07",
    description: "Session 07 stores many independently moving particles in one array, each with its own position, speed, and lifetime.",
    links: [
      { label: "Open Session 07", href: "sessions/session-07/", primary: true },
    ],
  },
  sessions: [
    {
      id: "session-01",
      kicker: "Session 01",
      title: "Drawing, Coordinates and First Functions",
      description: "Coordinates, shapes, and color become one reusable function that draws three faces instead of one.",
      duration: "2h 45m",
      tags: ["drawing", "coordinates", "functions"],
      href: "sessions/session-01/",
      links: [
        { label: "Open session page", href: "sessions/session-01/", primary: true },
      ],
    },
    {
      id: "session-02",
      kicker: "Session 02",
      title: "Variables, Mouse Input and Mapping",
      description: "Named values that change every frame, mouse position, and map() driving color and movement.",
      duration: "2h 45m",
      tags: ["variables", "mouse", "map()"],
      href: "sessions/session-02/",
      links: [
        { label: "Open session page", href: "sessions/session-02/", primary: true },
      ],
    },
    {
      id: "session-03",
      kicker: "Session 03",
      title: "Conditionals, Movement and State",
      description: "A sketch changes its own position every frame, and if statements decide when direction and color change.",
      duration: "2h 45m",
      tags: ["conditionals", "movement", "state"],
      href: "sessions/session-03/",
      links: [
        { label: "Open session page", href: "sessions/session-03/", primary: true },
      ],
    },
    {
      id: "session-04",
      kicker: "Session 04",
      title: "Loops, Grids and Waves",
      description: "One loop repeats a shape, two loops build a grid that reacts, and sin() turns repetition into a wave.",
      duration: "2h 45m",
      tags: ["loops", "grids", "waves"],
      href: "sessions/session-04/",
      links: [
        { label: "Open session page", href: "sessions/session-04/", primary: true },
      ],
    },
    {
      id: "session-05",
      kicker: "Session 05",
      title: "Functions, Parameters and Generative Systems",
      description: "One reusable function, called many times with different parameters and randomness, becomes a generative system.",
      duration: "2h 45m",
      tags: ["functions", "parameters", "generative"],
      href: "sessions/session-05/",
      links: [
        { label: "Open session page", href: "sessions/session-05/", primary: true },
      ],
    },
    {
      id: "session-06",
      kicker: "Session 06",
      title: "Noise and Recursion",
      description: "noise() reads smooth, related variation instead of random jumps, and a function that calls itself grows a branching tree.",
      duration: "2h 45m",
      tags: ["noise()", "recursion", "generative"],
      href: "sessions/session-06/",
      links: [
        { label: "Open session page", href: "sessions/session-06/", primary: true },
      ],
    },
    {
      id: "session-07",
      kicker: "Session 07",
      title: "Arrays, Objects and Particles",
      description: "One array stores many independently moving particles, each an object with its own position, speed, and lifetime.",
      duration: "2h 45m",
      tags: ["arrays", "objects", "particles"],
      href: "sessions/session-07/",
      links: [
        { label: "Open session page", href: "sessions/session-07/", primary: true },
      ],
    },
  ],
  sketches: [
    {
      id: "face-exercise",
      title: "Face Exercise",
      session: "Session 01",
      page: "web/face-exercise/index.html",
      source: "source/session-01/face-exercise/face-exercise.pde",
      description: "See how one reusable function draws three faces at different sizes.",
      try: "change the eye offsets, add a parameter, or call drawFace() again.",
      tags: ["functions", "drawing"],
      difficulty: "intro",
      related: ["mouse-shapes"],
    },
    {
      id: "color-house",
      title: "Color House",
      session: "Session 02",
      page: "web/color-house/index.html",
      source: "source/session-02/color-house/color-house.pde",
      description: "Click to see two variables change, then watch the drawing follow.",
      try: "change the random ranges, or randomize a third variable.",
      tags: ["mousePressed()", "state"],
      difficulty: "intro",
      related: ["mouse-shapes"],
    },
    {
      id: "mouse-shapes",
      title: "Mouse Shapes",
      session: "Session 02",
      page: "web/mouse-shapes/index.html",
      source: "source/session-02/mouse-shapes/mouse-shapes.pde",
      description: "Move the pointer to see mouseX and mouseY drive position and color through map().",
      try: "change a map() output range, or add a click-driven variable.",
      tags: ["mouseX", "map()", "variables"],
      difficulty: "intro",
      related: ["face-exercise", "color-house"],
    },
    {
      id: "hover-color",
      title: "Hover Color",
      session: "Session 03",
      page: "web/hover-color/index.html",
      source: "source/session-03/hover-color/hover-color.pde",
      description: "One shape and one if statement: is the mouse inside it?",
      try: "change the hover distance, or change what counts as hovering.",
      tags: ["if", "boolean", "conditionals"],
      difficulty: "intro",
      related: ["bouncing-ball"],
    },
    {
      id: "bouncing-ball",
      title: "Bouncing Ball Color",
      session: "Session 03",
      page: "web/bouncing-ball/index.html",
      source: "source/session-03/bouncing-ball/bouncing-ball.pde",
      description: "A ball moves on its own every frame and changes direction and color when an edge condition becomes true.",
      try: "change the speed, the edge reaction, or what the color becomes on collision.",
      tags: ["conditionals", "movement", "state"],
      difficulty: "intro",
      related: ["hover-color", "hover-grid"],
    },
    {
      id: "loop-row",
      title: "Loop Row",
      session: "Session 04",
      page: "web/loop-row/index.html",
      source: "source/session-04/loop-row/loop-row.pde",
      description: "One line of drawing code, repeated by a for loop instead of copied by hand.",
      try: "change the loop count, or the spacing between shapes.",
      tags: ["for loop", "repetition"],
      difficulty: "intro",
      related: ["hover-grid"],
    },
    {
      id: "hover-grid",
      title: "Hover Grid",
      session: "Session 04",
      page: "web/hover-grid/index.html",
      source: "source/session-04/hover-grid/hover-grid.pde",
      description: "A nested loop builds a grid, and a condition lets each cell react to the mouse on its own.",
      try: "change the grid size, or the hover condition and its colors.",
      tags: ["nested loops", "grid", "conditionals"],
      difficulty: "intro",
      related: ["loop-row", "hover-color", "simple-waves"],
    },
    {
      id: "simple-waves",
      title: "Simple Waves",
      session: "Session 04",
      page: "web/simple-waves/index.html",
      source: "source/session-04/simple-waves/simple-waves.pde",
      description: "sin() turns a row of circles into a smooth, repeating wave.",
      try: "change the amplitude, spacing, or speed of the wave.",
      tags: ["sin()", "loops", "waves"],
      difficulty: "intro",
      related: ["loop-row", "hover-grid"],
    },
    {
      id: "shapes-function",
      title: "Shapes Function",
      session: "Session 05",
      page: "web/shapes-function/index.html",
      source: "source/session-05/shapes-function/shapes-function.pde",
      description: "Click to see one reusable function generate a new random composition.",
      try: "change a parameter range, the number of calls, or add a shape type.",
      tags: ["functions", "parameters", "random()"],
      difficulty: "intro",
      related: ["face-exercise"],
    },
    {
      id: "noise-grid",
      title: "Noise Grid",
      session: "Session 06",
      page: "web/noise-grid/index.html",
      source: "source/session-06/noise-grid/noise-grid.pde",
      description: "noise() gives a grid smooth, related variation instead of random jumps.",
      try: "change the noise scale, or use noise() to control a different property.",
      tags: ["noise()", "grid"],
      difficulty: "intro",
      related: ["hover-grid", "recursive-tree"],
    },
    {
      id: "recursive-tree",
      title: "Recursive Tree",
      session: "Session 06",
      page: "web/recursive-tree/index.html",
      source: "source/session-06/recursive-tree/recursive-tree.pde",
      description: "A function that calls itself grows a whole branching tree from one small rule.",
      try: "change the branch-length multiplier, the angle, or the stopping threshold.",
      tags: ["recursion", "base case"],
      difficulty: "intro",
      related: ["noise-grid"],
    },
    {
      id: "array-of-dots",
      title: "Array of Dots",
      session: "Session 07",
      page: "web/array-of-dots/index.html",
      source: "source/session-07/array-of-dots/array-of-dots.pde",
      description: "Click to add a dot and see one array hold many positions.",
      try: "change the dot size or color, or track a second value per dot.",
      tags: ["arrays", "push()"],
      difficulty: "intro",
      related: ["particles-follow"],
    },
    {
      id: "particles-follow",
      title: "Particles Follow",
      session: "Session 07",
      page: "web/particles-follow/index.html",
      source: "source/session-07/particles-follow/particles-follow.pde",
      description: "Move the mouse to see an array of Particle objects appear, move, and fade away.",
      try: "change a starting value, the movement, or the lifetime.",
      tags: ["arrays", "classes", "particles"],
      difficulty: "intro",
      related: ["array-of-dots", "bouncing-ball"],
    },
  ],
  slides: [],
  searchExtras: [
    {
      type: "project",
      title: "Project Brief 1 - Interactive Visual Composition",
      href: "projects/index.html#brief-1",
      description: "Make something that responds to the viewer, after Sessions 01-03.",
      keywords: "project brief interactive composition mouse conditionals state",
    },
    {
      type: "project",
      title: "Project Brief 2 - Generative Visual System",
      href: "projects/index.html#brief-2",
      description: "Design a rule that produces a family of related results, after Sessions 04-06.",
      keywords: "project brief generative system loops functions random noise recursion",
    },
    {
      type: "project",
      title: "Final Project",
      href: "projects/index.html#final-project",
      description: "One focused personal work, after Session 07. Complexity is not the goal.",
      keywords: "final project synthesis assessment",
    },
  ],
};
